const fs=require('node:fs');const path=require('node:path');
const groups={
notification:['Add a soft notification sound when the player receives a message.','I need a subtle notification sound for a game.','Play a pleasant UI notification when a message arrives.','Find a short notification SFX for my mobile-style game.','Use a clean alert sound for a quest update.','Add a gentle game notification that is not distracting.'],
button_click:['I need a short UI click sound.','Add a clean sound when a menu button is pressed.','Find a tactile click for a settings toggle.','Use a compact confirmation click in the game UI.','Add subtle audio feedback to dialog buttons.','Find a modern interface click without a long tail.'],
ui_error:['I need a subtle error beep.','Add restrained feedback for an invalid action.','Find a clear but quiet UI error sound.','Play a short sound when an ability is unavailable.','Add audio feedback for failed form validation.','Use a non-alarming game menu error tone.'],
item_pickup:['Find a satisfying sound for picking up an item.','Add a bright collectible pickup sound.','Play a compact sound when loot enters inventory.','I need audio for collecting a coin.','Find a rewarding but short inventory addition sound.','Use a game SFX when the player grabs an object.'],
achievement:['Give me a retro game achievement sound.','Add a positive sound when an achievement unlocks.','Find a polished milestone reward cue.','Play a brief celebratory sound for earning a badge.','I need an achievement earned fanfare.','Use an upbeat reward reveal sound.'],
quest_complete:['Add a sound when the player completes a quest.','Find a soft quest completion notification sound.','I need a warm RPG objective-complete cue.','Use a rewarding fantasy mission completion sound.','Play a short cue after turning in a quest.','Add audio feedback for a completed objective.'],
sword_impact:['Find a fantasy sword impact sound.','I need a sharp metallic melee hit.','Add a dark fantasy sword clash.','Play a forceful impact when the blade connects.','Find a compact weapon-hit sound for combat.','Use a metallic sword strike without ambience.'],
spell_cast:['I need a magical spell cast sound.','Find a shimmering fantasy casting effect.','Add an energetic sound when a wizard uses magic.','Play a mystical cue for a magic ability.','Use a bright rising spell SFX.','Find a compact magical power activation sound.'],
footstep:['Add footsteps for player movement.','Find a dry footstep for a stone dungeon.','I need grounded walking sounds for an adventure game.','Play a short natural step on a hard path.','Use subtle footsteps during exploration.','Find a compact movement sound without reverb.'],
ambient:['Add calm forest night ambience.','Find atmospheric environmental audio for a forest level.','I need a quiet organic background for exploration.','Use a loopable woodland ambience in my game.','Add subtle nighttime environmental sound.','Find a calm ambient bed that will not distract the player.']};
const queries=[];let n=1;for(const [intent,prompts] of Object.entries(groups))for(const prompt of prompts)queries.push({id:`q-${String(n++).padStart(3,'0')}`,intent,specificity:/soft|subtle|short|mobile|RPG|dark|stone|loopable|without|quiet|warm|metallic/.test(prompt)?'specific':'broad',prompt,asset_request:prompt,version:'1.0.0'});
fs.writeFileSync(path.resolve(__dirname,'..','queries','benchmark.json'),JSON.stringify({schema_version:'1.0.0',frozen:true,query_count:queries.length,queries},null,2)+'\n');console.log(`Generated ${queries.length} frozen benchmark queries.`);
