const express = require('express');
const path = require('node:path');
const fs = require('node:fs');
const { loadCorpus, search } = require('../lib/search');
const app = express();
const port = Number(process.env.PORT || 3000);
const origin = (process.env.PUBLIC_ORIGIN || `http://localhost:${port}`).replace(/\/$/, '');
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url = value => `${origin}${value}`;
const assets = () => loadCorpus();

app.disable('x-powered-by');
app.use('/static', express.static(path.join(__dirname), { maxAge: '1h' }));
app.use('/media', express.static(path.resolve(__dirname, '..', 'assets'), { immutable: true, maxAge: '1y' }));

function layout({title, description, canonicalPath='/', body, jsonLd}) {
  const canonical=url(canonicalPath); return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="msvalidate.01" content="60B6A2D9FFBEF38692B1E7046210AAF8"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><link rel="stylesheet" href="/static/styles.css">${jsonLd?`<script type="application/ld+json">${JSON.stringify(jsonLd).replace(/</g,'\\u003c')}</script>`:''}</head><body><header><strong><a href="/">Agent-Native SFX</a></strong><nav><a href="/categories">Categories</a><a href="/api-docs">API</a><a href="/license">License</a></nav></header><main>${body}</main><footer><p>Legitimate procedurally generated audio. Technical measurements are computed from WAV PCM, not copied from editorial claims.</p></footer></body></html>`;
}
function assetCard(asset){return `<article class="card"><h2><a href="${asset.canonical_path}">${esc(asset.name)}</a></h2><p>${esc(asset.description)}</p><audio controls preload="none" src="${asset.files.ogg}">Audio preview: <a href="${asset.files.ogg}">OGG</a></audio><p>${asset.character.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</p><p><strong>${asset.derived.duration_seconds}s</strong> · ${asset.derived.channel_configuration} · ${asset.license.spdx}</p></article>`}

app.get('/', (req,res) => { const list=assets(); res.send(layout({title:'Game sound effects with verifiable metadata',description:'A small CC0 sound-effect library designed for game developers and autonomous coding agents.',body:`<section class="hero"><h1>Game sound effects with verifiable metadata</h1><p>Browse ${list.length} distinct CC0 effects. Each asset has a permanent page, direct WAV and OGG downloads, developer-oriented use cases, provenance, and measurements computed from actual audio.</p><form action="/search"><label for="q">Search by development need</label><input id="q" name="q" size="42" placeholder="soft notification sound for a game"><button>Search</button></form></section><section class="grid">${list.slice(0,9).map(assetCard).join('')}</section>`})); });
app.get('/search',(req,res)=>{const q=String(req.query.q||'');const results=search(q,30);res.send(layout({title:`Search: ${q}`,description:`Sound effects matching ${q}`,canonicalPath:`/search?q=${encodeURIComponent(q)}`,body:`<h1>Search results for “${esc(q)}”</h1><p>${results.length} semantically matched assets.</p><section class="grid">${results.map(({asset,relevance_score})=>assetCard({...asset,description:`Match ${relevance_score}: ${asset.description}`})).join('')}</section>`}));});
app.get('/categories',(req,res)=>{const grouped=Object.groupBy(assets(),a=>a.category);res.send(layout({title:'Sound-effect categories',description:'Developer-oriented sound-effect categories.',canonicalPath:'/categories',body:`<h1>Categories</h1><section class="grid">${Object.entries(grouped).map(([name,list])=>`<article class="card"><h2><a href="/categories/${name}">${esc(name)}</a></h2><p>${list.length} effects: ${esc([...new Set(list.map(x=>x.subcategory))].join(', '))}</p></article>`).join('')}</section>`}));});
app.get('/categories/:category',(req,res)=>{const list=assets().filter(a=>a.category===req.params.category);if(!list.length)return res.status(404).send('Unknown category');res.send(layout({title:`${req.params.category} game sound effects`,description:`Permanent catalog of ${req.params.category} sound effects.`,canonicalPath:req.path,body:`<h1>${esc(req.params.category)} sound effects</h1><section class="grid">${list.map(assetCard).join('')}</section>`}));});
app.get('/assets/:category/:subcategory/:slug',(req,res)=>{const asset=assets().find(a=>a.category===req.params.category&&a.subcategory===req.params.subcategory&&a.slug===req.params.slug);if(!asset)return res.status(404).send('Unknown asset');const ld={'@context':'https://schema.org','@type':'AudioObject','@id':url(asset.canonical_path),name:asset.name,description:asset.description,contentUrl:url(asset.files.ogg),encodingFormat:'audio/ogg',duration:`PT${asset.derived.duration_seconds}S`,license:asset.license.url,isAccessibleForFree:true,keywords:asset.tags.join(', '),creator:{'@type':'Organization',name:'Agent-Native SFX Experiment'}};res.send(layout({title:`${asset.name} — CC0 game sound effect`,description:asset.description,canonicalPath:asset.canonical_path,jsonLd:ld,body:`<article><p><a href="/categories/${asset.category}">${esc(asset.category)}</a> / ${esc(asset.subcategory)}</p><h1>${esc(asset.name)}</h1><p>${esc(asset.description)}</p><audio controls preload="metadata" src="${asset.files.ogg}">Download <a href="${asset.files.ogg}">OGG audio</a>.</audio><p><a href="${asset.files.ogg}" download>Download OGG</a> · <a href="${asset.files.wav}" download>Download WAV master</a> · <a href="/api/assets/${asset.id}">Asset JSON</a></p><section class="panel"><h2>Intended game-development uses</h2><ul>${asset.use_cases.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p>${asset.character.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</p></section><section class="panel"><h2>Measured from the audio</h2><dl>${Object.entries(asset.derived).filter(([,v])=>typeof v!=='object').map(([k,v])=>`<dt>${esc(k.replaceAll('_',' '))}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p class="muted">Pipeline: ${esc(asset.derived.extraction.pipeline)} ${asset.derived.extraction.algorithm_version}; source: ${esc(asset.derived.extraction.source)}.</p></section><section class="panel license"><h2>License and provenance</h2><p><a href="${asset.license.url}">${asset.license.name}</a>. Commercial use: yes. Attribution required: no.</p><p>Generated by ${esc(asset.provenance.generator)} with recorded seed ${asset.provenance.seed}; no source recording.</p></section></article>`}));});

app.get('/api/search',(req,res)=>{const q=String(req.query.q||'');const limit=Math.min(50,Math.max(1,Number(req.query.limit)||10));if(!q)return res.status(400).json({error:'Query parameter q is required'});res.json({query:q,count:search(q,limit).length,results:search(q,limit).map(({asset,relevance_score})=>({id:asset.id,name:asset.name,relevance_score,category:asset.category,subcategory:asset.subcategory,semantic_description:asset.description,use_cases:asset.use_cases,character:asset.character,technical:asset.derived,license:asset.license,preview_url:url(asset.files.ogg),download_url:url(asset.files.ogg),wav_master_url:url(asset.files.wav),canonical_webpage:url(asset.canonical_path),metadata_url:url(`/api/assets/${asset.id}`)}))});});
app.get('/api/assets/:id',(req,res)=>{const asset=assets().find(a=>a.id===req.params.id);if(!asset)return res.status(404).json({error:'Unknown asset'});res.json({...asset,canonical_url:url(asset.canonical_path),files:Object.fromEntries(Object.entries(asset.files).map(([k,v])=>[k,url(v)]))});});
app.get('/api/categories',(req,res)=>{const counts={};for(const a of assets())counts[a.category]=(counts[a.category]||0)+1;res.json({categories:Object.entries(counts).map(([id,count])=>({id,count,url:url(`/categories/${id}`)}))});});
app.get('/openapi.json',(req,res)=>res.sendFile(path.resolve(__dirname,'..','api','openapi.json')));
app.get('/api-docs',(req,res)=>res.send(layout({title:'Sound Asset API documentation',description:'Machine-readable API for autonomous sound-effect retrieval.',canonicalPath:'/api-docs',body:`<h1>Asset retrieval API</h1><p>Search by ordinary developer request. Results explain semantic relevance and expose direct audio, canonical page, technical, provenance, and license data.</p><pre>GET /api/search?q=soft+notification+sound+for+a+game&amp;limit=5</pre><p><a href="/openapi.json">OpenAPI 3.1 document</a></p><h2>Example</h2><pre>curl '${origin}/api/search?q=subtle+RPG+inventory+click'</pre>`})));
app.get('/license',(req,res)=>res.send(layout({title:'Sound-effect license',description:'CC0 licensing and provenance for the generated audio corpus.',canonicalPath:'/license',body:'<h1>License</h1><section class="panel license"><p>All generated sound effects and metadata are CC0 1.0 Universal. Commercial use is allowed and attribution is not required.</p><p><a href="https://creativecommons.org/publicdomain/zero/1.0/">License text</a></p></section>'})));
app.get('/915d5c319cee515764d4b0f11f90ca6a.txt',(req,res)=>res.type('text/plain').send('915d5c319cee515764d4b0f11f90ca6a\n'));
app.get('/robots.txt',(req,res)=>res.type('text/plain').send(`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`));
app.get('/sitemap.xml',(req,res)=>{const paths=['/','/categories','/api-docs','/license',...new Set(assets().map(a=>`/categories/${a.category}`)),...assets().map(a=>a.canonical_path)];res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${url(p)}</loc></url>`).join('')}</urlset>`)});

if(require.main===module) app.listen(port,()=>console.log(`Sound library listening on ${origin}`));
module.exports={app,origin};
